<?php
declare(strict_types=1);
$base=dirname(__DIR__);$cfgFile=__DIR__.'/private/discovery-config.json';$candFile=__DIR__.'/private/candidates.json';$obsFile=__DIR__.'/private/observations-private.json';$logFile=__DIR__.'/discovery-last-run.json';
$cfg=json_decode((string)file_get_contents($cfgFile),true,512,JSON_THROW_ON_ERROR);if(empty($cfg['enabled'])){echo "Discovery disabled\n";exit;}
$cands=json_decode((string)file_get_contents($candFile),true,512,JSON_THROW_ON_ERROR);$obs=json_decode((string)file_get_contents($obsFile),true,512,JSON_THROW_ON_ERROR);
$known=[];foreach($obs['observations'] as $o)$known[canonical($o['source'])]=$o;foreach($cands['candidates'] as $i=>$c)$candIndex[canonical($c['url'])]=$i;$events=[];
function canonical(string $u):string{$p=parse_url($u);if(!$p)return $u;$path=rtrim($p['path']??'','/');return strtolower(($p['scheme']??'https').'://'.($p['host']??'').$path);}
function fetch(string $u,int $timeout,string $ua='RGPD-Tariff-Discovery/1.0 (+https://rgpd.lepotager.org/comparateur/)'):string|false{$ctx=stream_context_create(['http'=>['timeout'=>$timeout,'follow_location'=>1,'max_redirects'=>4,'header'=>"User-Agent: $ua\r\nAccept: text/html,application/rss+xml,application/xml\r\n"]]);return @file_get_contents($u,false,$ctx);}
function textonly(string $html):string{$html=preg_replace('#<(script|style|noscript)\b[^>]*>.*?</\1>#is',' ',$html);return preg_replace('/\s+/u',' ',html_entity_decode(strip_tags($html),ENT_QUOTES|ENT_HTML5,'UTF-8'));}
function prices(string $t):array{preg_match_all('/(?<!\d)(\d{1,3}(?:[\s\x{00A0}.]\d{3})*(?:[,.]\d{1,2})?)\s*€\s*(?:HT|TTC)?(?:\s*\/\s*(?:jour|mois|an|traitement))?/iu',$t,$m);$a=array_values(array_unique(array_slice($m[0]??[],0,12)));return $a;}
function contains_any(string $text,array $terms):bool{$l=mb_strtolower($text);foreach($terms as $t)if(str_contains($l,mb_strtolower($t)))return true;return false;}
function detect_region(string $t,array $cfg):array{$l=mb_strtolower($t);foreach($cfg['regional_terms']['57'] as $x)if(str_contains($l,mb_strtolower($x)))return ['region'=>'moselle','department'=>'57'];foreach($cfg['regional_terms']['grand-est'] as $x)if(str_contains($l,mb_strtolower($x)))return ['region'=>'grand-est','department'=>''];return ['region'=>'unknown','department'=>''];}
function classify(string $t,array $cfg):string{if(contains_any($t,$cfg['reject_terms']))return 'reject';if(contains_any($t,$cfg['dpo_terms']))return 'dpo';if(contains_any($t,$cfg['legal_terms']))return 'legal';return contains_any($t,$cfg['service_terms'])?'market':'reject';}
function bing_rss(string $q,array $cfg):array{$url='https://www.bing.com/search?format=rss&q='.rawurlencode($q);$xml=fetch($url,(int)$cfg['timeout_seconds']);if($xml===false)return[];$sx=@simplexml_load_string($xml);if(!$sx)return[];$out=[];foreach($sx->channel->item??[] as $i=>$it){if($i>=(int)$cfg['max_results_per_query'])break;$out[]=['url'=>(string)$it->link,'title'=>(string)$it->title,'snippet'=>(string)$it->description];}return $out;}
function searxng(string $q,array $cfg):array{$base=rtrim((string)$cfg['searxng_url'],'/');if(!$base)return[];$raw=fetch($base.'/search?q='.rawurlencode($q).'&format=json',(int)$cfg['timeout_seconds']);if($raw===false)return[];$j=json_decode($raw,true);$out=[];foreach(array_slice($j['results']??[],0,(int)$cfg['max_results_per_query']) as $r)$out[]=['url'=>$r['url'],'title'=>$r['title']??'','snippet'=>$r['content']??''];return $out;}
$queries=[];foreach(['moselle','grand-est','france'] as $zone)foreach($cfg['queries'][$zone]??[] as $q)$queries[]=[$zone,$q];
foreach($queries as [$zone,$q]){$results=$cfg['provider']==='searxng'?searxng($q,$cfg):bing_rss($q,$cfg);foreach($results as $r){$url=$r['url'];if(!filter_var($url,FILTER_VALIDATE_URL))continue;$key=canonical($url);if(isset($known[$key])||isset($candIndex[$key]))continue;$page=fetch($url,(int)$cfg['timeout_seconds']);if($page===false)continue;$text=textonly($page);if(!contains_any($text,$cfg['service_terms']))continue;$class=classify($text,$cfg);$reg=detect_region($text.' '.$r['snippet'],$cfg);$ps=prices($text);$status=$class==='reject'?'rejected':(count($ps)?'new':'monitored_no_price');$id='auto-'.substr(hash('sha256',$key),0,12);$entry=['id'=>$id,'url'=>$url,'title'=>trim($r['title'])?:parse_url($url,PHP_URL_HOST),'status'=>$status,'region'=>$reg['region'],'department'=>$reg['department'],'city'=>'','classification_hint'=>$class,'price_candidates'=>$ps,'reason'=>$status==='new'?'Nouvelle source tarifaire détectée automatiquement — validation humaine obligatoire.':($status==='monitored_no_price'?'Source RGPD détectée sans tarif exploitable — surveillance maintenue.':'Hors périmètre selon les règles déterministes.'),'discovered_at'=>date('Y-m-d'),'source'=>'search:'.$q];$cands['candidates'][]=$entry;$candIndex[$key]=count($cands['candidates'])-1;$events[]=['status'=>'candidate','url'=>$url,'class'=>$class,'region'=>$reg['region'],'prices'=>$ps];usleep((int)$cfg['request_delay_ms']*1000);}}
$cands['updated_at']=date(DATE_ATOM);$tmp=$candFile.'.tmp';file_put_contents($tmp,json_encode($cands,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);rename($tmp,$candFile);file_put_contents($logFile,json_encode(['finished_at'=>date(DATE_ATOM),'events'=>$events],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),LOCK_EX);echo 'OK — '.count($events)." nouvelle(s) piste(s)\n";
